name: CI Workflow

on: [pull_request]

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: variavel
        env:
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_PORT: ${{secrets.DB_PORT}}
      run: |
        echo "POSTGRES_USER: $POSTGRES_USER"
        echo "POSTGRES_DB: $POSTGRES_DB"
        echo "DB_HOST: $DB_HOST"
        echo "DB_PORT: $DB_PORT"
        # Não imprimir oo POSTGRES_PASSWORD Por questões de segurança;

      - name: Install requirements
        run: pip install -r requirements-dev.txt

      - name: List directory contents
        run: ls -la

      - name: Run tests
        run: pytest -v